# Nome do Workflow
name: 'ServiceNow - Scan Branch Changes'

# Gatilho: Roda quando uma Pull Request é aberta ou atualizada para a branch 'main'
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-branch-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ---------------------------------------------------------------------
      # IMPORTANTE: Normalmente, haveria um passo aqui para aplicar
      # as mudanças da branch (ex: Update Set) na instância de scan.
      # Essa etapa geraria o sys_id do Update Set como um output.
      # Exemplo (usando outra action do ServiceNow):
      #
      # - name: Apply Update Set to Test Instance
      #   id: apply_changes # Damos um ID para referenciar o output depois
      #   uses: ServiceNow/sncicd-apply-changes@v2
      #   with:
      #     # ...parâmetros de conexão...
      #     updateSetSysId: 'SYS_ID_DO_UPDATE_SET_DO_DESENVOLVEDOR'
      #
      # O output seria acessado com: ${{ steps.apply_changes.outputs.updateSetSysId }}
      # Para este exemplo, vamos usar um sys_id fixo, mas você deve automatizar isso.
      # ---------------------------------------------------------------------

      - name: Run ServiceNow Instance Scan on Update Set
        uses: ServiceNow/sncicd-instance-scan@v2
        with:
          # Credenciais (as mesmas de antes)
          instanceUrl: ${{ secrets.SN_INSTANCE_URL }}
          instanceUsername: ${{ secrets.SN_USERNAME }}
          instancePassword: ${{ secrets.SN_PASSWORD }}

          # --- Parâmetros de Scan para a Branch ---

          # 1. Tipo de Scan: 'suite_update' para escanear Update Sets
          scanType: 'suite_update'

          # 2. ID da Suíte de Scans: Qual conjunto de regras usar?
          #    Você precisa pegar este sys_id da sua instância.
          suiteSysId: '532840af20a70110fa9b96e15935cc77' # Exemplo: "Development Best Practices"

          # 3. ID do Update Set: O sys_id do Update Set que contém as mudanças da branch.
          #    O ideal é que este valor venha de um passo anterior no pipeline.
          updateSetSysIds: '24b462f19380321046e4ff8ddd03d622'
          # Exemplo automatizado: updateSetSysIds: ${{ steps.apply_changes.outputs.appliedUpdateSetSysId }}
