# Nome do Workflow
name: 'ServiceNow - Scan Branch on PR'

# Gatilho: Roda quando uma Pull Request é aberta ou atualizada para a branch 'main'
on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # Permite rodar manualmente também

jobs:
  scan-pull-request-changes:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer o checkout do código do SEU repositório.
      # Este passo é OBRIGATÓRIO porque a sua action ("uses: ./...") é local.
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Passo 2 (Placeholder): Obter o sys_id do Update Set da branch.
      # Em um pipeline real, este passo seria substituído por uma automação
      # que aplica o Update Set em uma instância de teste e retorna o sys_id.
      - name: 'Placeholder: Get Update Set Sys ID'
        id: get_update_set
        run: echo "updateset_sysid=24b462f19380321046e4ff8ddd03d622" >> $GITHUB_OUTPUT

      # Passo 3: Executar a sua action de scan local
      - name: ServiceNow CI/CD Instance Scan
        # Usando a sua action local, como no seu exemplo
        uses: ./.github/actions/scan
        id: scan
        with:
          # --- Parâmetros Adaptados para Pull Request ---

          # 1. Mude o scantype para escanear um Update Set
          scantype: 'suite_update'

          # 2. Forneça o sys_id da Suíte de Scan que você quer usar
          #    (Encontre em Instance Scan > Scan Suites na sua instância)
          suiteSysId: '532840af20a70110fa9b96e15935cc77' # Exemplo: "Development Best Practices"

          # 3. Forneça o sys_id do Update Set que veio do passo anterior
          updateSetSysIds: ${{ steps.get_update_set.outputs.updateset_sysid }}

          # Removemos os outros parâmetros (targetTable, appScopeSysIds, etc.)
          # porque eles não são necessários para o scantype 'suite_update'.

        # Atenção: Usando as variáveis de ambiente do seu exemplo
        env:
          nowUsername: ${{ secrets.NOW_USERNAME }}
          nowPassword: ${{ secrets.NOW_PASSWORD }}
          nowScanInstance: ${{ secrets.NOW_SCAN_INSTANCE }}
